# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Masonry111' do
pod 'Masonry', '~> 0.6.3'

end


